version: '3'

services:

  nc-wef:
    restart: always
    image: dpjl/nc-wef:main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test1:/shared1
      - ./test2:/shared2
    environment:
      - SHARED_FOLDER_1=/shared1
      - OWNERS_1={"dav":"admin"}
      - SHARED_FOLDER_2=/shared2
      - OWNERS_2={"dav":"admin"}

